### ISSUE TITLE
git2 blame is slow

### ISSUE THREAD

**Issue by brandonedens** [Arrowbox/git-whoknows#2]
It turns out that git2 blame is slow; using an obsolete algorithm to construct its information. Due to a licensing issue git2 will not be incorporating the later algorithm from git. Finally, no-one has addressed the issue in git2. This can be read about here:
https://github.com/libgit2/libgit2/issues/3027
Here's the changes:
https://github.com/git/git/commit/7e6ac6e4391caa0fc379cb699013d503380e4214

I recommend switching to invoking `git blame --line-porcelain` in a subprocess and parsing / accumulating the results as its significantly faster.

**Comment by Arrowbox** [comment]
That was my thoughts too. I'll see if I can leave the usage of git2 with a cli toggle.

**Comment by brandonedens** [comment]
Here's a nom solution.
https://github.com/brandonedens/git-whoknows/tree/blame-porcelain
Its a little bit behind the times compared to current master and I can bring it up to date.
It'll always be correct and faster I'd imagine than the regex.

I modified main.rs quite a bit and made a HashMap<Author, Vec<Commit>> in preparation for using something like DashMap for concurrent updating of the author details.

**Comment by brandonedens** [comment]
Here is performance comparison of Linux kernel ./CREDITS file
```
Benchmark #1: git blame --porcelain CREDITS
  Time (mean ± σ):      1.103 s ±  0.013 s    [User: 1.012 s, System: 0.090 s]
  Range (min … max):    1.076 s …  1.116 s    10 runs

Benchmark #1: /tmp/git-whoknows_18e641b7312201285cbaa615b0307a14d1568f50 CREDITS
  Time (mean ± σ):      1.177 s ±  0.006 s    [User: 1.070 s, System: 0.110 s]
  Range (min … max):    1.171 s …  1.190 s    10 runs

Benchmark #1: /tmp/git-whoknows_blame-porcelain CREDITS
  Time (mean ± σ):      1.132 s ±  0.009 s    [User: 1.037 s, System: 0.094 s]
  Range (min … max):    1.120 s …  1.142 s    10 runs
```
The version git-whoknows_e96768f57cf5de3e03803ed4f07e51ed60bc2df2 didn't complete in any reasonable amount of time so I abandoned testing it.

**Comment by brandonedens** [comment]
Here's another benchmark now with the latest branch nom-blame-parser.
```
linux on  master 
❯ hyperfine 'git blame --porcelain fs/nfs/nfs4proc.c' 'git blame --line-porcelain fs/nfs/nfs4proc.c' 'git-whoknows fs/nfs/nfs4proc.c' 'git-whoknows --nom fs/nfs/nfs4proc.c'
Benchmark #1: git blame --porcelain fs/nfs/nfs4proc.c
  Time (mean ± σ):      2.548 s ±  0.053 s    [User: 2.418 s, System: 0.124 s]
  Range (min … max):    2.437 s …  2.624 s    10 runs
 
Benchmark #2: git blame --line-porcelain fs/nfs/nfs4proc.c
  Time (mean ± σ):      2.602 s ±  0.008 s    [User: 2.479 s, System: 0.119 s]
  Range (min … max):    2.595 s …  2.618 s    10 runs
 
Benchmark #3: git-whoknows fs/nfs/nfs4proc.c
  Time (mean ± σ):      2.714 s ±  0.015 s    [User: 2.585 s, System: 0.136 s]
  Range (min … max):    2.698 s …  2.743 s    10 runs
 
Benchmark #4: git-whoknows --nom fs/nfs/nfs4proc.c
  Time (mean ± σ):      2.556 s ±  0.012 s    [User: 2.421 s, System: 0.132 s]
  Range (min … max):    2.535 s …  2.572 s    10 runs
 
Summary
  'git blame --porcelain fs/nfs/nfs4proc.c' ran
    1.00 ± 0.02 times faster than 'git-whoknows --nom fs/nfs/nfs4proc.c'
    1.02 ± 0.02 times faster than 'git blame --line-porcelain fs/nfs/nfs4proc.c'
    1.07 ± 0.02 times faster than 'git-whoknows fs/nfs/nfs4proc.c'
```

**Comment by brandonedens** [comment]
I'm going to close this issue. The software is much faster now.
